### ISSUE TITLE
gpio12 w/ sd card

### ISSUE THREAD

**Issue by lbernstone** [LilyGO/TTGO-T5-ePaper1.54#3]
SD cards have an internal pull up on all pins.  This means that pin 12 gets pulled up if you have an sd card in the device at boot.  gpio12 is the MTDI pin, HIGH indicates that the device should boot as an SDIO slave, and prevents booting the programmed firmware.  Please use a different pin for DAT2.

**Comment by lbernstone** [comment]
For reference, GPIO12 boot behavior can be disabled. https://github.com/espressif/esp-idf/tree/master/examples/storage/sd_card#note-about-gpio12

**Comment by novusabeo** [comment]
How does one disable it? Having the same problem using the ESP32 example sketch on arduino IDE for SD Test

**Comment by novusabeo** [comment]
Still can't get it to work. Tried the eFuse burn and gpio_pullup_dis(GPIO_NUM_12);
How were you able to get it work? Trying to use it to read bitmaps to the screen/read data in general using the provided ESP32 SD test example on Arduino IDE/PlatformIO
